### ISSUE TITLE
window is undefined and result is NULL in combination with Next.JS

### ISSUE THREAD

**Issue by sixtyniner-official** [Johann-S/bs-breakpoints#5] opened 2019-06-04 07:34 UTC
I've tried to use a package in Next.JS project with server-side rendering SSR.

On first reload `window is not defined` error is thrown.

When a component is rendered, state value for a breakpoint is `null`

![component](https://user-images.githubusercontent.com/14074280/58860217-ede13600-86ab-11e9-8d5c-9359b44fa8f1.png)

**Comment by Johann-S** [comment] 2019-06-04 08:15
Hi @mestro67,

First of all thanks for using my plugin 👍 

It seems it's a specificty of Next.js, but you'll find some workarounds here: https://github.com/zeit/next.js/wiki/FAQ

My libs need to access the `window` object because it adds a polyfill for IE users if needed. I do that because I follow Bootstrap 4 browser support

**Comment by Johann-S** [comment] 2019-06-06 07:21
did you find a solution @mestro67 ?

**Comment by iaroslavshvets** [comment] 2021-02-01 15:25
Hi! Getting same issue. I think, that the root cause is that library code is evaluated on the stage of defining import and not after calling init(). I did a workaround by importing library via dynamic import inside `useEffect` by it looks ugly and it requires to do the same trick every time you use it inside a new file/component and work with lib as a Promise like thing. Can we lazy-evaluate stuff that needs window upon `init` call?

**Comment by Johann-S** [comment] 2024-07-29 19:48
it should be fixed in v2: https://github.com/Johann-S/bs-breakpoints/releases/tag/v2.0.0

**Closed as completed by Johann-S** 2024-07-29 19:48 UTC
Labels: awaiting reply
